services:
  # Frontend - Static Site
  - type: web
    name: smartjewel-frontend
    env: static
    buildCommand: cd smartjewel-frontend && npm install && npm run build
    staticPublishPath: smartjewel-frontend/dist
    envVars:
      - key: VITE_API_BASE
        value: https://smart-jewel.vercel.app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
